version: "3.9"

services:
  mariadb:
    image: mariadb:10.5   # versi stabil yg cocok dengan PHP 5.x
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appnet

  php:
    build: ./php
    container_name: php-fpm
    restart: always
    volumes:
      - ./src:/var/www/html
    networks:
      - appnet

  nginx:
    image: nginx:stable
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php
    networks:
      - appnet

volumes:
  db_data:

networks:
  appnet:
